# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0002_auto_20161007_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='code',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
